### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ajueid** [GambitBSM/gambit_1.2#1]
Dear Gambit developers,

I tried to install Gambit on my machine (Ubuntu 18.04) but I ran into the following errors which stop the installation.

examples/CMakeFiles/MCMCAlgo.dir/build.make:161: recipe for target 'bin/MCMCAlgo' failed

 80%] No update step for 'diver_1.0.4'
[ 80%] Performing verify step for 'diver_1.0.4'
[ 80%] No patch step for 'diver_1.0.4'
[ 80%] No configure step for 'diver_1.0.4'
[ 80%] Performing build step for 'diver_1.0.4'
make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[ 80%] No install step for 'diver_1.0.4'
[100%] Completed 'diver_1.0.4'
[100%] Built target diver_1.0.4
CMakeFiles/Makefile2:6419: recipe for target 'CMakeFiles/scanners.dir/rule' failed
make[1]: *** [CMakeFiles/scanners.dir/rule] Error 2
Makefile:2601: recipe for target 'scanners' failed
make: *** [scanners] Error 2

PS: I have installed all the packages required by Gambit (where the list of the packages were found in the README.md file). 

Thanks a lot for your help,
Adil

**Comment by ajueid** [comment]
Here is the output of cmake command 

-- Build type is set to None 
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "3")
   Using Python interpreter version 3.6.8 for build.
   PythonLibs NOT found, so pybind11 cannot be used. Ditching support for Python backends.
   If you *do* have the Python libraries installed, you should first try setting/unsetting
   FORCE_PYTHON2 or FORCE_PYTHON3 when invoking cmake (make sure to clean out your build
   directory in between any such changes).  If that does not work, you can manually set the
   following variables when invoking cmake (also making sure to clean out your build dir):
     PYTHON_LIBRARY
     PYTHON_INCLUDE_DIR
     PYTHON_INCLUDE_DIR2 (you might be able to get away without setting this one)
     PYTHON_EXECUTABLE   (you might be able to get away without setting this one)
-- Found Python module yaml.
-- Found Python module os.
-- Found Python module re.
-- Found Python module datetime.
-- Found Python module sys.
-- Found Python module getopt.
-- Found Python module shutil.
-- Found Python module itertools.
   Found axel. Backend and scanner downloads will be as fast as possible.
-- Boost version: 1.59.0
-- Eigen version: 3.3.5
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP_Fortran: -fopenmp  
-- Found OpenMP: TRUE   
   Missing library libuuid required for WSTP. Mathematica will be disabled.
-- Werror is disabled
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
-- Could NOT find MPI_Fortran (missing: MPI_Fortran_LIB_NAMES MPI_Fortran_F77_HEADER_DIR MPI_Fortran_MODULE_DIR MPI_Fortran_WORKS) 
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND MPI_Fortran_FOUND) 
   Missing C MPI installation.  GAMBIT will not be MPI-enabled.
   Missing Fortran MPI installation.  Fortran scanners will not be MPI-enabled.
   Missing C++ MPI installation.  C++ scanners will not be MPI-enabled.
-- A library with BLAS API found.
-- A library with LAPACK API found.
   Using the following LAPACK libraries: /usr/lib/x86_64-linux-gnu/liblapack.so /usr/lib/x86_64-linux-gnu/libblas.so
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5 libraries: /home/adil/anaconda2/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/home/adil/anaconda2/lib/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so
--  (missing: SQLITE3_LIBRARY SQLITE3_INCLUDE_DIR) 
   No SQLite C libraries found. Excluding sqliteprinter and sqlitereader from GAMBIT configuration.
   GAMBIT version detected from git tag: 1.4.1
-- RestFrames-dependent analyses in ColliderBit will be activated.
   RestFrames library not found. RestFrames v1.0.2 will be downloaded and installed when building GAMBIT.
-- Configuring FlexibleSUSY for models: MDM,CMSSM,MSSM,MSSMatMGUT,MSSM_mAmu,MSSMatMSUSY_mAmu,MSSMatMGUT_mAmu,MSSMEFTHiggs,MSSMEFTHiggs_mAmu,MSSMatMSUSYEFTHiggs_mAmu,MSSMatMGUTEFTHiggs,MSSMatMGUTEFTHiggs_mAmu,ScalarSingletDM_Z3,ScalarSingletDM_Z2
-- Configuring FlexibleSUSY - done.
-- Updating GAMBIT scanner cmake and related files
   Found library ./ScannerBit/installed/diver/1.0.4/lib/libdiver.so needed for ScannerBit plugin diver v1.0.4
   Found library ./build/great_1.0.0-prefix/src/great_1.0.0-build/lib/libgreat.so needed for ScannerBit plugin great v1.0.0
   Found include path /home/adil/Work/gambit_1.4/ScannerBit/installed/great/1.0.0/Manager/include needed for ScannerBit plugin great v1.0.0
   Found include path /home/adil/Work/gambit_1.4/ScannerBit/installed/great/1.0.0/MCMC/include needed for ScannerBit plugin great v1.0.0
   Found include path /home/adil/Work/gambit_1.4/ScannerBit/installed/great/1.0.0/fparser4.5.1 needed for ScannerBit plugin great v1.0.0
   Found library ./ScannerBit/installed/multinest/3.11/libnest3.so needed for ScannerBit plugin multinest v3.11.0
   Found library ./ScannerBit/installed/polychord/1.15/lib/libchord.so needed for ScannerBit plugin polychord v1.15.0
   Existing ScannerBit/include/gambit/ScannerBit/priors_rollcall.hpp is identical to candidate; leaving it untouched
   Updated ScannerBit/CMakeLists.txt
   Existing ScannerBit/lib/plugin_libraries.list is identical to candidate; leaving it untouched
   Updated scratch/scanbit_reqd_entries.yaml
   Existing scratch/scanbit_flags.yaml is identical to candidate; leaving it untouched
   Existing /home/adil/Work/gambit_1.4/build/linkedout.cmake is identical to candidate; leaving it untouched
-- Updating GAMBIT scanner cmake and related files - done.
-- Updating GAMBIT with config data
   Found graphviz. Model and module function hierarchy plots will be enabled.
   Configured /home/adil/Work/gambit_1.4/cmake/include/gambit/cmake/cmake_variables.hpp
-- Updating GAMBIT with config data - done.
-- Generated particle_database.cpp from particle_database.yaml.
-- Updating GAMBIT module, model, backend, and printer CMake files.
   Existing ExampleBit_A/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing ColliderBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing ExampleBit_B/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing FlavBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing DecayBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing DarkBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing SpecBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing PrecisionBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing NeutrinoBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing Backends/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing Models/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing Printers/CMakeLists.txt is identical to candidate; leaving it untouched
-- Updating GAMBIT module, backend, and printer CMake files - done.
 X Excluding susyhd 1.0.2 from GAMBIT configuration.
-- BOSS step successfully generated for the following cmake targets: pythia_8.212;pythia_8.212.EM;gm2calc_1.3.0;gm2calc_1.2.0 
-- Did not find scanner library diver for diver_1.0.0. Disabling scanners that depend on this.
-- Did not find scanner library diver for diver_1.0.2. Disabling scanners that depend on this.
-- Found scanner header: /TGreatModel.h
-- Found scanner header: /TGreatMCMCAlgorithmCovariance.h
-- Found scanner header: /fparser.hh
-- Found scanner header: /TGreatManager.h
-- Did not find scanner library nest3 for multinest_3.10. Disabling scanners that depend on this.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/adil/Work/gambit_1.4/build

I have all the python libraries installed so I am not sure why it's displaying this message "PythonLibs NOT found, so pybind11 cannot be used. Ditching support for Python backends."

**Comment by patscott** [comment]
Hi Adil,

please install the latest version of GAMBIT (1.4.1), and raise an issue on that repository if you still have issues.  This version (1.2) is no longer supported.  You can find 1.4 here:

https://github.com/patscott/gambit_1.4

Best wishes - Pat
