### ISSUE TITLE
CMakeFiles/Makefile2:5972: recipe for target 'CMakeFiles/scanners.dir/rule' failed make[1]: *** [CMakeFiles/scanners.dir/rule] Error 2

### ISSUE THREAD

**Issue by qxxgouzei** [GambitBSM/gambit_1.2#2]

**Comment by patscott** [comment]
Hi - thanks for trying out GAMBIT.

This version of GAMBIT (1.2) is no longer supported; please try with version 1.4, found here: https://github.com/patscott/gambit_1.4/

Also, please note that 
a) you don't need the `make scanners` command to complete successfully in order to build gambit
b) `make scanners` is just a shortcut for making all the individual scanners.  So the error you have pasted here is not the actual error that you got when trying to build one of the scanners, it's just an error from the Makefile saying that something failed to build.  Please make the individual scanners, or read the full error message that is produced when `make scanners` fails, identify the scanner that failed and the error that it gives, and paste that into a new issue on the 1.4 repository (if you still see the same problem with v1.4)
c) GreAT will often fail due to ROOT installation bugs.  Please see this thread:  https://github.com/patscott/gambit_1.4/issues/1

Best wishes - Pat

**Comment by qxxgouzei** [comment]
> Hi - thanks for trying out GAMBIT.
> 
> This version of GAMBIT (1.2) is no longer supported; please try with version 1.4, found here: https://github.com/patscott/gambit_1.4/
> 
> Also, please note that
> a) you don't need the `make scanners` command to complete successfully in order to build gambit
> b) `make scanners` is just a shortcut for making all the individual scanners. So the error you have pasted here is not the actual error that you got when trying to build one of the scanners, it's just an error from the Makefile saying that something failed to build. Please make the individual scanners, or read the full error message that is produced when `make scanners` fails, identify the scanner that failed and the error that it gives, and paste that into a new issue on the 1.4 repository (if you still see the same problem with v1.4)
> c) GreAT will often fail due to ROOT installation bugs. Please see this thread: [patscott/gambit_1.4#1](https://github.com/patscott/gambit_1.4/issues/1)
> 
> Best wishes - Pat
 l am glad to hear from you , i download the newest version of gambit , i try to make scanners and get the following error :
[ 33%] Performing verify step for 'multinest_3.11'
[ 33%] No update step for 'multinest_3.11'
[ 33%] No patch step for 'multinest_3.11'
[ 66%] Performing configure step for 'multinest_3.11'
[ 66%] Performing build step for 'multinest_3.11'
/usr/bin/ld: /usr/local/lib/liblapack.a(dpotrf2.o): relocation R_X86_64_PC32 against symbol `dpotrf2_' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: 最后的链结失败: 错误的值
collect2: error: ld returned 1 exit status
Makefile:39: recipe for target 'libnest3.so' failed
make[4]: *** [libnest3.so] Error 1
CMakeFiles/multinest_3.11.dir/build.make:118: recipe for target 'multinest_3.11-prefix/src/multinest_3.11-stamp/multinest_3.11-build' failed
make[3]: *** [multinest_3.11-prefix/src/multinest_3.11-stamp/multinest_3.11-build] Error 2
CMakeFiles/Makefile2:450: recipe for target 'CMakeFiles/multinest_3.11.dir/all' failed
make[2]: *** [CMakeFiles/multinest_3.11.dir/all] Error 2
CMakeFiles/Makefile2:5972: recipe for target 'CMakeFiles/scanners.dir/rule' failed
make[1]: *** [CMakeFiles/scanners.dir/rule] Error 2
Makefile:2432: recipe for target 'scanners' failed
make: *** [scanners] Error 2
 maybe i can ignore "make scanners" command like your first suggestion?

**Comment by qxxgouzei** [comment]
i try make gambit directly ,but i got the following error:
sed: -e 表达式 #6, 字符 19: 未终止的“s”命令↵
sed: -e 表达式 #6, 字符 19: 未终止的“s”命令↵
sed: -e 表达式 #6, 字符 19: 未终止的“s”命令↵
sed: -e 表达式 #6, 字符 19: 未终止的“s”命令↵
[ 17%] Performing build step for 'flexiblesusy'
make[4]: *** 没有规则可制作目标“alllib”。 停止。
CMakeFiles/flexiblesusy.dir/build.make:110: recipe for target 'flexiblesusy-prefix/src/flexiblesusy-stamp/flexiblesusy-build' failed
make[3]: *** [flexiblesusy-prefix/src/flexiblesusy-stamp/flexiblesusy-build] Error 2
CMakeFiles/Makefile2:6253: recipe for target 'CMakeFiles/flexiblesusy.dir/all' failed
make[2]: *** [CMakeFiles/flexiblesusy.dir/all] Error 2
CMakeFiles/Makefile2:138: recipe for target 'CMakeFiles/gambit.dir/rule' failed
make[1]: *** [CMakeFiles/gambit.dir/rule] Error 2
Makefile:131: recipe for target 'gambit' failed
make: *** [gambit] Error 2

**Comment by patscott** [comment]
Ah, it's because your version of LAPACK is the static library.  You need the shared library to compile gambit (and to make multinest - which is the first error you got).  So you need to uninstall the static version of LAPACK and install the shared one.  

What version of cmake are you using?  Normally cmake detects that you have the wrong version of LAPACK and gives a sensible error telling you that it is the wrong version.  Can you also paste the output of your cmake command (run in an empty build directory) please?

**Comment by qxxgouzei** [comment]
thanks a lot ,i will try and my cmake version is  3.10.2 ， my cmake result is as followed ,this is the result of static  lapack libaray
-- Build type is set to None 
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- The Fortran compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.8", minimum required is "3") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.8", minimum required is "3") 
   Using Python interpreter version 3.6.8 for build.
   Using Python libraries version 3.6.8 for Python backend support.
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.8") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.2.4
   Found pybind11 2.2.4 at /home/qxx/gambit/contrib/pybind11.
-- Found Python module yaml.
-- Found Python module os.
-- Found Python module re.
-- Found Python module datetime.
-- Found Python module sys.
-- Found Python module getopt.
-- Found Python module shutil.
-- Found Python module itertools.
   Found axel. Backend and scanner downloads will be as fast as possible.
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Boost version: 1.66.0
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "3.1.0") 
-- Eigen version: 3.3.4
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gsl >= 1.15'
--   Found gsl , version 2.4
-- Found GSL: ;/usr/local/lib/libgsl.so;/usr/local/lib/libgslcblas.so;/usr/lib/x86_64-linux-gnu/libm.so  
   Found library libuuid
-- Found Mathematica_WSTP: /usr/local/Wolfram/Mathematica/11.0/SystemFiles/Links/WSTP/DeveloperKit/Linux-x86-64/CompilerAdditions/libWSTP64i4.so (found version "4.25") 
-- Found Mathematica_MathLink: /usr/local/Wolfram/Mathematica/11.0/SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions/libML64i4.so (found version "4.37") 
-- Found Mathematica_WolframLibrary: /usr/local/Wolfram/Mathematica/11.0/SystemFiles/Libraries/Linux-x86-64/libWolframRTL.so (found version "3") 
-- Found Mathematica_JLink: /usr/local/Wolfram/Mathematica/11.0/SystemFiles/Links/JLink (found version "4.9.1") 
-- Found Mathematica_MUnit: /usr/local/Wolfram/Mathematica/11.0/SystemFiles/Components/MUnit (found version "1.4.0") 
-- Found Mathematica: /usr/local/Wolfram/Mathematica/11.0 (found suitable version "11.0.0.0", minimum required is "10.0") 
   Found Mathematica.
   Found Wolfram Symbolic Transfer Protocol. Mathematica backends enabled.
-- Found LibDL: /usr/lib/x86_64-linux-gnu/libdl.so  
-- Werror is disabled
-- Performing Test CXX_SUPPORTS_all
-- Performing Test CXX_SUPPORTS_all - Success
-- Performing Test CXX_SUPPORTS_extra
-- Performing Test CXX_SUPPORTS_extra - Success
-- Performing Test CXX_SUPPORTS_no-misleading-indentation
-- Performing Test CXX_SUPPORTS_no-misleading-indentation - Success
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI_Fortran: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempif08.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI C/C++ libraries found. GAMBIT will be MPI-enabled.
-- MPI Fortran libraries found. Fortran scanners will be MPI-enabled.
-- MPI C++ libraries found. C++ scanners will be MPI-enabled.
-- Looking for Fortran dgemm
-- Looking for Fortran dgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
   Using the following LAPACK libraries: /usr/local/lib/liblapack.a /usr/lib/x86_64-linux-gnu/libf77blas.so /usr/lib/x86_64-linux-gnu/libatlas.so
-- Could NOT find ROOT (missing: ROOT_CONFIG_EXECUTABLE ROOTSYS ROOT_VERSION ROOT_INCLUDE_DIR ROOT_LIBRARIES ROOT_LIBRARY_DIR) (Required is at least version "6")
   No ROOT 6 installation found. Excluding GreAT and RestFrames from GAMBIT configuration. 
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5 libraries: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so
--  (missing: SQLITE3_LIBRARY SQLITE3_INCLUDE_DIR) 
   No SQLite C libraries found. Excluding sqliteprinter and sqlitereader from GAMBIT configuration.
-- Found Git: /usr/bin/git (found version "2.24.0") 
fatal: 没有发现名称，无法描述任何东西。
   GAMBIT version not detected via git.  Reverting to cmake/tarball_info.cmake.
 X Excluding RestFrames from GAMBIT configuration. (ROOT was not found.)
   RestFrames-dependent analyses in ColliderBit will be deactivated.
-- Performing Test CXX_SUPPORTS_no-deprecated-declarations
-- Performing Test CXX_SUPPORTS_no-deprecated-declarations - Success
-- Performing Test CXX_SUPPORTS_no-unused-parameter
-- Performing Test CXX_SUPPORTS_no-unused-parameter - Success
-- Performing Test CXX_SUPPORTS_no-unused-variable
-- Performing Test CXX_SUPPORTS_no-unused-variable - Success
-- Configuring FlexibleSUSY for models: MDM,CMSSM,MSSM,MSSMatMGUT,MSSM_mAmu,MSSMatMSUSY_mAmu,MSSMatMGUT_mAmu,MSSMEFTHiggs,MSSMEFTHiggs_mAmu,MSSMatMSUSYEFTHiggs_mAmu,MSSMatMGUTEFTHiggs,MSSMatMGUTEFTHiggs_mAmu,ScalarSingletDM_Z3,ScalarSingletDM_Z2
sed: -e 表达式 #6, 字符 19: 未终止的“s”命令↵
sed: -e 表达式 #6, 字符 19: 未终止的“s”命令↵
sed: -e 表达式 #6, 字符 19: 未终止的“s”命令↵
sed: -e 表达式 #6, 字符 19: 未终止的“s”命令↵
-- Configuring FlexibleSUSY - done.
-- Updating GAMBIT scanner cmake and related files
   Found library ./ScannerBit/installed/diver/1.0.4/lib/libdiver.so needed for ScannerBit plugin diver v1.0.4
   Existing ScannerBit/include/gambit/ScannerBit/priors_rollcall.hpp is identical to candidate; leaving it untouched
   Updated ScannerBit/CMakeLists.txt
   Existing ScannerBit/lib/plugin_libraries.list is identical to candidate; leaving it untouched
   Existing scratch/scanbit_reqd_entries.yaml is identical to candidate; leaving it untouched
   Existing scratch/scanbit_flags.yaml is identical to candidate; leaving it untouched
   Created /home/qxx/gambit/build/linkedout.cmake
-- Updating GAMBIT scanner cmake and related files - done.
-- Updating GAMBIT with config data
-- Looking for include file link.h
-- Looking for include file link.h - found
   Found graphviz. Model and module function hierarchy plots will be enabled.
   Configured /home/qxx/gambit/cmake/include/gambit/cmake/cmake_variables.hpp
-- Updating GAMBIT with config data - done.
-- Generated particle_database.cpp from particle_database.yaml.
-- Updating GAMBIT module, model, backend, and printer CMake files.
   Existing FlavBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing NeutrinoBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing DarkBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing ColliderBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing SpecBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing DecayBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing ExampleBit_A/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing PrecisionBit/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing ExampleBit_B/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing Backends/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing Models/CMakeLists.txt is identical to candidate; leaving it untouched
   Existing Printers/CMakeLists.txt is identical to candidate; leaving it untouched
-- Updating GAMBIT module, backend, and printer CMake files - done.
-- Performing Test CXX_SUPPORTS_no-extra
-- Performing Test CXX_SUPPORTS_no-extra - Success
 X Excluding great 1.0.0 from GAMBIT configuration.
-- BOSS step successfully generated for the following cmake targets: pythia_8.212;pythia_8.212.EM;gm2calc_1.3.0;gm2calc_1.2.0 
 X Excluding great 1.0.0 from ScannerBit configuration.
-- Did not find scanner library diver for diver_1.0.0. Disabling scanners that depend on this.
-- Did not find scanner library diver for diver_1.0.2. Disabling scanners that depend on this.
-- Did not find scanner library great for great. Disabling scanners that depend on this.
-- Did not find scanner header fparser.hh. Disabling scanners that depend on this.
-- Did not find scanner header TGreatManager.h. Disabling scanners that depend on this.
-- Did not find scanner header TGreatMCMCAlgorithmCovariance.h. Disabling scanners that depend on this.
-- Did not find scanner header TGreatModel.h. Disabling scanners that depend on this.
-- Did not find scanner library nest3 for multinest_3.10. Disabling scanners that depend on this.
-- Did not find scanner library nest3 for multinest_3.11. Disabling scanners that depend on this.
-- Did not find scanner library chord for polychord. Disabling scanners that depend on this.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/qxx/gambit/build

**Comment by patscott** [comment]
Fixed the cmake issue with detecting the static version of LAPACK in [v1.4.2](https://github.com/patscott/gambit_1.4/releases/tag/v1.4.2)

**Comment by qxxgouzei** [comment]
i will have a try thanks a lot

**Comment by qxxgouzei** [comment]
i try to install the v1.4.2 in my computer and when i cmake i get the following error:
-- Build type is set to None 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
   Using Python interpreter version 3.6.9 for build.
   Using Python libraries version 3.6.9 for Python backend support.
-- pybind11 v2.2.4
   Found pybind11 2.2.4 at /home/qxx/gambit/contrib/pybind11.
-- Found Python module yaml.
-- Found Python module os.
-- Found Python module re.
-- Found Python module datetime.
-- Found Python module sys.
-- Found Python module getopt.
-- Found Python module shutil.
-- Found Python module itertools.
   Found axel. Backend and scanner downloads will be as fast as possible.
-- Boost version: 1.66.0
-- Eigen version: 3.3.4
   Found library libuuid
   Found Mathematica.
   Found Wolfram Symbolic Transfer Protocol. Mathematica backends enabled.
-- Werror is disabled
-- MPI C/C++ libraries found. GAMBIT will be MPI-enabled.
-- MPI Fortran libraries found. Fortran scanners will be MPI-enabled.
-- MPI C++ libraries found. C++ scanners will be MPI-enabled.
-- A library with BLAS API found.
-- A library with LAPACK API found.
   Using the following LAPACK libraries: /usr/local/lib/liblapack.a /usr/lib/x86_64-linux-gnu/libf77blas.so /usr/lib/x86_64-linux-gnu/libatlas.so
CMake Error at cmake/optional.cmake:173 (message):
  LAPACK static library detected.  Shared LAPACK libraries are
  required in order to build GAMBIT.
Call Stack (most recent call first):
  CMakeLists.txt:391 (include)


-- Configuring incomplete, errors occurred!
See also "/home/qxx/gambit/build/CMakeFiles/CMakeOutput.log".

**Comment by patscott** [comment]
Good, thanks, that's the correct behaviour on your system then (where the static LAPACK libs are installed).

**Comment by qxxgouzei** [comment]
liblapack: /usr/lib/x86_64-linux-gnu/liblapack.so
 /usr/lib/x86_64-linux-gnu/liblapack.a 
/usr/lib/liblapack.a 
/usr/local/lib/liblapack.a

**Comment by patscott** [comment]
Not sure what you are trying to say by just pasting paths.  

If this is what you have installed, try getting rid of the static lib picked up by cmake (/usr/local/lib/liblapack.a).  It's probably just a link anyway, likely one you created by hand, as the standard packages wouldn't normally make this.  Alternatively, put some symbolic links to the .so version of the library wherever there are links to the .a version.

**Comment by qxxgouzei** [comment]
emem ,i am sorry to bother you too long time and  give the invalid reply , the above three path is where  my liblapack installed,  and in fact i have no idea to get rid of the static lib picked up by cmake .

**Comment by patscott** [comment]
You can try adding symbolic links to the .so file like I suggested above, i.e.

```
cd /usr/local/lib/ 
ln -s /usr/lib/x86_64-linux-gnu/liblapack.so
cd /usr/lib/ 
ln -s /usr/lib/x86_64-linux-gnu/liblapack.so

```

**Comment by patscott** [comment]
you may need to use `sudo`

**Comment by qxxgouzei** [comment]
thanks for your help and it worked ,but  i meet new problems when i cmake as followed:
CMake Error at cmake/contrib.cmake:50 (add_subdirectory):
  add_subdirectory given source "/home/qxx/gambit/contrib/yaml-cpp-0.6.2"
  which is not an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:417 (include)


 X Excluding RestFrames from GAMBIT configuration. (ROOT was not found.)
   RestFrames-dependent analyses in ColliderBit will be deactivated.
-- Performing Test CXX_SUPPORTS_no-deprecated-declarations
-- Performing Test CXX_SUPPORTS_no-deprecated-declarations - Success
-- Performing Test CXX_SUPPORTS_no-unused-parameter
-- Performing Test CXX_SUPPORTS_no-unused-parameter - Success
-- Performing Test CXX_SUPPORTS_no-unused-variable
-- Performing Test CXX_SUPPORTS_no-unused-variable - Success
-- Configuring FlexibleSUSY for models: MDM,CMSSM,MSSM,MSSMatMGUT,MSSM_mAmu,MSSMatMSUSY_mAmu,MSSMatMGUT_mAmu,MSSMEFTHiggs,MSSMEFTHiggs_mAmu,MSSMatMSUSYEFTHiggs_mAmu,MSSMatMGUTEFTHiggs,MSSMatMGUTEFTHiggs_mAmu,ScalarSingletDM_Z3,ScalarSingletDM_Z2
-- Configuring FlexibleSUSY failed.  Here's what I tried to do:
./configure;--with-cxx=/usr/bin/c++;--with-cxxflags= -fPIC -std=c++14 -fopenmp -Wall -Wextra -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-variable;--with-shared-ldflags=-fopenmp;--with-fc=/usr/bin/gfortran;--with-fflags= -fPIC -ffree-line-length-none -ffixed-line-length-none -cpp -fopenmp;--with-eigen-incdir=/usr/include/eigen3;--with-boost-libdir=;--with-boost-incdir=/usr/local/include;--with-lapack-libs=/usr/local/lib/liblapack.so /usr/lib/x86_64-linux-gnu/libf77blas.so /usr/lib/x86_64-linux-gnu/libatlas.so;--with-blas-libs=/usr/local/lib/liblapack.so /usr/lib/x86_64-linux-gnu/libf77blas.so /usr/lib/x86_64-linux-gnu/libatlas.so;--disable-librarylink;--enable-shared-libs;--with-shared-lib-ext=.so;--with-shared-lib-cmd=/usr/bin/c++  -shared -o;--with-models=MDM,CMSSM,MSSM,MSSMatMGUT,MSSM_mAmu,MSSMatMSUSY_mAmu,MSSMatMGUT_mAmu,MSSMEFTHiggs,MSSMEFTHiggs_mAmu,MSSMatMSUSYEFTHiggs_mAmu,MSSMatMGUTEFTHiggs,MSSMatMGUTEFTHiggs_mAmu,ScalarSingletDM_Z3,ScalarSingletDM_Z2

CMake Error at cmake/contrib.cmake:227 (message):
  Configuring FlexibleSUSY failed.
Call Stack (most recent call first):
  CMakeLists.txt:417 (include)


-- Configuring incomplete, errors occurred!
See also "/home/qxx/gambit/build/CMakeFiles/CMakeOutput.log".

**Comment by patscott** [comment]
Not sure; you seem to have deleted some of the installation or something strange like that.  Do you have the directory /home/qxx/gambit/contrib/yaml-cpp-0.6.2?  Is there a file CMakeLists.txt in it?  My advice would be to start the installation over from scratch.  Also to read the errors and messages that you get and to try to use those to help to resolve your issues.


On 04/12/2019 17:09, qxxgouzei wrote:

thanks for your help and it worked ,but i meet new problems when i cmake as followed:
CMake Error at cmake/contrib.cmake:50 (add_subdirectory):
add_subdirectory given source "/home/qxx/gambit/contrib/yaml-cpp-0.6.2"
which is not an existing directory.
Call Stack (most recent call first):
CMakeLists.txt:417 (include)

X Excluding RestFrames from GAMBIT configuration. (ROOT was not found.)
RestFrames-dependent analyses in ColliderBit will be deactivated.
-- Performing Test CXX_SUPPORTS_no-deprecated-declarations
-- Performing Test CXX_SUPPORTS_no-deprecated-declarations - Success
-- Performing Test CXX_SUPPORTS_no-unused-parameter
-- Performing Test CXX_SUPPORTS_no-unused-parameter - Success
-- Performing Test CXX_SUPPORTS_no-unused-variable
-- Performing Test CXX_SUPPORTS_no-unused-variable - Success
-- Configuring FlexibleSUSY for models: MDM,CMSSM,MSSM,MSSMatMGUT,MSSM_mAmu,MSSMatMSUSY_mAmu,MSSMatMGUT_mAmu,MSSMEFTHiggs,MSSMEFTHiggs_mAmu,MSSMatMSUSYEFTHiggs_mAmu,MSSMatMGUTEFTHiggs,MSSMatMGUTEFTHiggs_mAmu,ScalarSingletDM_Z3,ScalarSingletDM_Z2
-- Configuring FlexibleSUSY failed. Here's what I tried to do:
./configure;--with-cxx=/usr/bin/c++;--with-cxxflags= -fPIC -std=c++14 -fopenmp -Wall -Wextra -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-variable;--with-shared-ldflags=-fopenmp;--with-fc=/usr/bin/gfortran;--with-fflags= -fPIC -ffree-line-length-none -ffixed-line-length-none -cpp -fopenmp;--with-eigen-incdir=/usr/include/eigen3;--with-boost-libdir=;--with-boost-incdir=/usr/local/include;--with-lapack-libs=/usr/local/lib/liblapack.so /usr/lib/x86_64-linux-gnu/libf77blas.so /usr/lib/x86_64-linux-gnu/libatlas.so;--with-blas-libs=/usr/local/lib/liblapack.so /usr/lib/x86_64-linux-gnu/libf77blas.so /usr/lib/x86_64-linux-gnu/libatlas.so;--disable-librarylink;--enable-shared-libs;--with-shared-lib-ext=.so;--with-shared-lib-cmd=/usr/bin/c++ -shared -o;--with-models=MDM,CMSSM,MSSM,MSSMatMGUT,MSSM_mAmu,MSSMatMSUSY_mAmu,MSSMatMGUT_mAmu,MSSMEFTHiggs,MSSMEFTHiggs_mAmu,MSSMatMSUSYEFTHiggs_mAmu,MSSMatMGUTEFTHiggs,MSSMatMGUTEFTHiggs_mAmu,ScalarSingletDM_Z3,ScalarSingletDM_Z2

CMake Error at cmake/contrib.cmake:227 (message):
Configuring FlexibleSUSY failed.
Call Stack (most recent call first):
CMakeLists.txt:417 (include)

-- Configuring incomplete, errors occurred!
See also "/home/qxx/gambit/build/CMakeFiles/CMakeOutput.log".

**Comment by qxxgouzei** [comment]
there's no such directory /home/qxx/gambit/contrib/yaml-cpp-0.6.2 , i will have  a try
